version: '3.4'
services:

  # Grouping Services for dev purposes
  db:
    image: rwgrim/docker-noop
    depends_on: 
      - mongo-rs0-1
      - mongo-rs0-2
      - mongo-rs0-3
      - setup-rs
      - adminmongo
  zoo:
    image: rwgrim/docker-noop
    depends_on: 
      - zoo1
      - zoo2
      - zoo3
      - zoonav
      - zoonav-api
  storage:
    image: rwgrim/docker-noop
    depends_on: 
      - storage_1
      - storage_2
      - storage_3

  # Django Web APP
  web:
    build:
      context: ./web_app
      network: host
    hostname: web
    # initialization shell script
    # command: sh ./init.sh
    command: sh init.sh
    volumes:
      - ./web_app/django:/app
    ports:
       - "8000:8000"

  # Storage Servers
  storage_1:
    build:
      context: ./storage
      network: host
    hostname: storage_1
    # initialization shell script
    command: sh init.sh
    volumes:
      - ./storage/django:/app
      - ./storage/storage_1:/data
    ports:
      - "8001:8000"
    environment:
      STORAGE_ID: 1 
    depends_on:
      - zoo

  storage_2:
    build:
      context: ./storage
      network: host
    hostname: storage_2
    # initialization shell script
    command: sh init.sh
    volumes:
      - ./storage/django:/app
      - ./storage/storage_2:/data
    ports:
      - "8002:8000"
    environment:
      STORAGE_ID: 2 
    depends_on:
      - zoo
      
  storage_3:
    build:
      context: ./storage
      network: host
    hostname: storage_3
    # initialization shell script
    command: sh init.sh
    volumes:
      - ./storage/django:/app
      - ./storage/storage_3:/data
    ports:
      - "8003:8000"
    environment:
      STORAGE_ID: 3 
    depends_on:
      - zoo     

  # Zookeeper Ensemble
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_TICK_TIME: 2000

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
      ZOO_TICK_TIME: 2000

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
      ZOO_TICK_TIME: 2000

  # Web GUI for Zookeeper
  zoonav:
    image: elkozmon/zoonavigator-web:0.6.1
    container_name: zoonav
    ports:
     - "8080:8080"
    environment:
      WEB_HTTP_PORT: 8080
      API_HOST: "zoonav-api"
      API_PORT: 9000
    depends_on:
     - zoonav-api
    restart: always
  
  zoonav-api:
    image: elkozmon/zoonavigator-api:0.6.1
    container_name: zoonav-api
    environment:
      API_HTTP_PORT: 9000
    restart: always    

  # Mongo replica set    
  mongo-rs0-1:
    image: "mongo-start"
    build: ./mongo-rs0-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db

  # Docker to setup replica set and then die (:
  setup-rs:
    image: "setup-rs"
    build: ./setup-rs
    depends_on:
      - "mongo-rs0-1"
  
  # Admin page for mongoDB
  adminmongo:
    image: "adicom/admin-mongo"
    # First connection can be initialized with environment variables
    # Web connection syntax: mongodb://<user>:<password>@127.0.0.1:<port>/<db>
    # Web connection 1 string:  mongodb://mongo-rs0-1

    environment:
      # The name of the connection to create on boot
      CONN_NAME: mongo1
      # The username for the database connection
      # - DB_USERNAME=""
      # The password fot the database user
      # - DB_PASSWORD=""
      # The host IP address or DNS name without the port!      
      DB_HOST: mongo-rs0-1
      # The port of the mongoDB database, if not provided the default 27017 will be used      
      # - DB_PORT=
    ports:
      - "1234:1234"
    depends_on:
      - "mongo-rs0-1"